<a href="https://colab.research.google.com/github/Alino4kaAlino4ka/probability_theory_and_math_statistics/blob/main/probability_theory_dz_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Теория вероятностей и математическая статистика (семинары)

Урок 10. Дисперсионный анализ

Провести дисперсионный анализ для определения того, есть ли различия среднего роста среди взрослых футболистов, хоккеистов и штангистов.
Даны значения роста в трех группах случайно выбранных спортсменов:

Футболисты: 173, 175, 180, 178, 177, 185, 183, 182.

Хоккеисты: 177, 179, 180, 188, 177, 172, 171, 184, 180.

Штангисты: 172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170.

In [ ]:
import numpy as np
import pandas as pd
from scipy import stats
from statsmodels.stats.multicomp import pairwise_tukeyhsd

In [ ]:
ftb = np.array([173, 175, 180, 178, 177, 185, 183, 182])
hck = np.array([177, 179, 180, 188, 177, 172, 171, 184, 180])
brb = np.array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170])

ftb, hck, brb

(array([173, 175, 180, 178, 177, 185, 183, 182]),
 array([177, 179, 180, 188, 177, 172, 171, 184, 180]),
 array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170]))

In [ ]:
stats.shapiro(ftb)

ShapiroResult(statistic=0.9775081276893616, pvalue=0.9495397210121155)

In [ ]:
stats.shapiro(hck)

ShapiroResult(statistic=0.9579195976257324, pvalue=0.7763133645057678)

In [ ]:
stats.shapiro(brb)

ShapiroResult(statistic=0.93868088722229, pvalue=0.5051169991493225)

In [ ]:
stats.bartlett(ftb, hck, brb)

BartlettResult(statistic=0.4640521043406442, pvalue=0.7929254656083131)

In [ ]:
stats.kruskal(ftb, hck, brb)

KruskalResult(statistic=7.897493213863828, pvalue=0.01927885061595347)

In [ ]:
df = pd.DataFrame({"score":[173, 175, 180, 178, 177, 185, 183, 182, 
                         177, 179, 180, 188, 177, 172, 171, 184, 180, 
                         172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170], 
                 "group": np.repeat(["soccer_players","hockey_players","weightlifter"], repeats=(8, 9, 11))})
df

score           group
0     173  soccer_players
1     175  soccer_players
2     180  soccer_players
3     178  soccer_players
4     177  soccer_players
5     185  soccer_players
6     183  soccer_players
7     182  soccer_players
8     177  hockey_players
9     179  hockey_players
10    180  hockey_players
11    188  hockey_players
12    177  hockey_players
13    172  hockey_players
14    171  hockey_players
15    184  hockey_players
16    180  hockey_players
17    172    weightlifter
18    173    weightlifter
19    169    weightlifter
20    177    weightlifter
21    166    weightlifter
22    180    weightlifter
23    178    weightlifter
24    177    weightlifter
25    172    weightlifter
26    166    weightlifter
27    170    weightlifter

In [ ]:
tukey = pairwise_tukeyhsd(df["score"], df["group"], alpha=0.05)
print(tukey)

         Multiple Comparison of Means - Tukey HSD, FWER=0.05         
    group1         group2     meandiff p-adj   lower    upper  reject
---------------------------------------------------------------------
hockey_players soccer_players   0.4583    0.9  -5.3555  6.2722  False
hockey_players   weightlifter  -5.9394 0.0283 -11.3172 -0.5616   True
soccer_players   weightlifter  -6.3977 0.0218 -11.9573 -0.8382   True
---------------------------------------------------------------------


In [ ]:
stats.f_oneway(ftb, hck, brb)  # функция однофакторного анализа

F_onewayResult(statistic=5.500053450812596, pvalue=0.010482206918698694)