<a href="https://colab.research.google.com/github/Alino4kaAlino4ka/probability_theory_and_math_statistics/blob/main/probability_theory_dz_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Теория вероятностей и математическая статистика (семинары)

Урок 7. Непараметрические тесты

1-4 задачи решать с помощью функций, 5ю вручную

Выбрать тест и проверить, есть  ли различия между выборками:


---

1 )  Даны две  независимые выборки. Не соблюдается условие нормальности

x1  380,420, 290

y1 140,360,200,900

Сделайте вывод по результатам, полученным с помощью функции

In [ ]:
import scipy.stats as stats
import numpy as np

In [ ]:
x1 = np.array([380, 420, 290])
y1 = np.array([140, 360, 200, 900])

x1, y1

(array([380, 420, 290]), array([140, 360, 200, 900]))

In [ ]:
stats.mannwhitneyu(x1, y1)

MannwhitneyuResult(statistic=8.0, pvalue=0.6285714285714286)

---
---
2 ) Исследовалось влияние препарата на уровень давления пациентов. Сначала измерялось давление до приема препарата, потом через 10 минут и через 30 минут. Есть ли статистически значимые различия?

1е измерение до приема препарата: 150, 160, 165, 145, 155

2е измерение через 10 минут: 140, 155, 150,  130, 135

3е измерение через 30 минут: 130, 130, 120, 130, 125

In [ ]:
arr1 = np.array([150, 160, 165, 145, 155])
arr2 = np.array([140, 155, 150, 130, 135])
arr3 = np.array([130, 130, 120, 130, 125])

arr1, arr2, arr3

(array([150, 160, 165, 145, 155]),
 array([140, 155, 150, 130, 135]),
 array([130, 130, 120, 130, 125]))

In [ ]:
stats.friedmanchisquare(arr1, arr2, arr3)

FriedmanchisquareResult(statistic=9.578947368421062, pvalue=0.00831683351100441)

---
---
---
3 ) Сравните 1 и 2 е измерения, предполагая, что 3го измерения через 30 минут не было

In [ ]:
stats.wilcoxon(arr1, arr2)

WilcoxonResult(statistic=0.0, pvalue=0.0625)

---
---
---
---
4) Даны 3 группы  учеников плавания.

В 1 группе время на дистанцию 50 м составляют: 56, 60, 62, 55, 71, 67, 59, 58, 64, 67

Вторая группа : 57, 58, 69, 48, 72, 70, 68, 71, 50, 53

Третья группа: 57, 67, 49, 48, 47, 55, 66, 51, 54

In [ ]:
arr1 = np.array([56, 60, 62, 55, 71, 67, 59, 58, 64, 67])
arr2 = np.array([57, 58, 69, 48, 72, 70, 68, 71, 50, 53])
arr3 = np.array([57, 67, 49, 48, 47, 55, 66, 51, 54])

arr1, arr2, arr3

(array([56, 60, 62, 55, 71, 67, 59, 58, 64, 67]),
 array([57, 58, 69, 48, 72, 70, 68, 71, 50, 53]),
 array([57, 67, 49, 48, 47, 55, 66, 51, 54]))

In [ ]:
stats.kruskal(arr1, arr2, arr3)

KruskalResult(statistic=5.465564058257224, pvalue=0.0650380998590494)

---
---
---
---
---
5) Заявляется, что партия изготавливается со средним арифметическим 2,5 см. Проверить данную гипотезу, если известно, что размеры изделий подчинены нормальному закону распределения. Объем выборки 10, уровень статистической значимости 5%

2.51, 2.35, 2.74, 2.56, 2.40, 2.36, 2.65, 2.7, 2.67, 2.34

In [ ]:
arr = np.array([2.51, 2.35, 2.74, 2.56, 2.40, 2.36, 2.65, 2.7, 2.67, 2.34])
arr

array([2.51, 2.35, 2.74, 2.56, 2.4 , 2.36, 2.65, 2.7 , 2.67, 2.34])

In [ ]:
m = arr.mean()
m

2.5279999999999996

In [ ]:
l = len(arr)
l

10

In [ ]:
arr_std = arr.std(ddof=1)
arr_std

0.1572542173961923

In [ ]:
t = (m - 2.5) / (arr_std / np.sqrt(l))
t

0.5630613661802959

th = (x - mu) / (sigma mu / np.sqrt(n))

In [ ]:
# th = (x - mu) / (sigma mu / np.sqrt(n))

In [ ]:
stats.ttest_1samp(arr, 2.5)

Ttest_1sampResult(statistic=0.5630613661802959, pvalue=0.5871439993940628)